
project_id = "kunmckljzbnqjaswihou"
[functions.create-checkout]
verify_jwt = true
[functions.customer-portal]
verify_jwt = true
[functions.stripe-webhook]
verify_jwt = false
[functions.send-email]
verify_jwt = false
[functions.auth-hook]
verify_jwt = false
