// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kunmckljzbnqjaswihou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bm1ja2xqemJucWphc3dpaG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAyMzE1ODIsImV4cCI6MjA0NTgwNzU4Mn0.TqmKi2HK9Ngzo0FHAwG9fsKpM1x1r26x2zWaI0rluoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);